import java.awt.Color;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author laboratorio
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        getContentPane().setBackground(new Color(10, 12, 30));
        //setExtendedState(MAXIMIZED_BOTH);
        
        Veiculo v1 = new Veiculo();
        corVeiculo.setText(v1.getCorVeiculo());
        nomeVeiculo.setText(v1.getNomeVeiculo());
        anoFabricacaoVeiculo.setText(v1.getAnoFabricacaoVeiculo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        corVeiculo = new javax.swing.JLabel();
        nomeVeiculo = new javax.swing.JLabel();
        anoFabricacaoVeiculo = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(0, 153, 153));
        setLocation(new java.awt.Point(500, 200));
        setPreferredSize(new java.awt.Dimension(800, 600));

        corVeiculo.setBackground(new java.awt.Color(51, 255, 0));
        corVeiculo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        corVeiculo.setForeground(new java.awt.Color(51, 204, 255));
        corVeiculo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        corVeiculo.setText("COR");
        corVeiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        nomeVeiculo.setBackground(new java.awt.Color(51, 255, 0));
        nomeVeiculo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        nomeVeiculo.setForeground(new java.awt.Color(51, 204, 255));
        nomeVeiculo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nomeVeiculo.setText("NOME");
        nomeVeiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        anoFabricacaoVeiculo.setBackground(new java.awt.Color(51, 255, 0));
        anoFabricacaoVeiculo.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        anoFabricacaoVeiculo.setForeground(new java.awt.Color(51, 204, 255));
        anoFabricacaoVeiculo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        anoFabricacaoVeiculo.setText("FABRICACAO");
        anoFabricacaoVeiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        Titulo.setFont(new java.awt.Font("Yu Gothic Medium", 0, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(0, 153, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("ATRIBUTOS DO VEÍCULO");
        Titulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(corVeiculo)
                        .addGap(91, 91, 91))
                    .addComponent(nomeVeiculo)
                    .addComponent(anoFabricacaoVeiculo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(Titulo)
                .addGap(74, 74, 74)
                .addComponent(nomeVeiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(corVeiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anoFabricacaoVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel anoFabricacaoVeiculo;
    private javax.swing.JLabel corVeiculo;
    private javax.swing.JLabel nomeVeiculo;
    // End of variables declaration//GEN-END:variables
}
