/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Exercicio01;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author laboratorio
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    public Interface() {
        initComponents();
        getContentPane().setBackground(new Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        valor1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        soma = new javax.swing.JButton();
        subtracao = new javax.swing.JButton();
        multiplicacao = new javax.swing.JButton();
        divisao = new javax.swing.JButton();
        inputV2 = new javax.swing.JTextField();
        inputV1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        resultadoCalculo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CALCULADORA");

        valor1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        valor1.setText("Valor 1:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Valor 2:");

        soma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        soma.setText("+");
        soma.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        soma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        soma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                somaActionPerformed(evt);
            }
        });

        subtracao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        subtracao.setText("-");
        subtracao.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        subtracao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtracaoActionPerformed(evt);
            }
        });

        multiplicacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        multiplicacao.setText("x");
        multiplicacao.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        multiplicacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        multiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplicacaoActionPerformed(evt);
            }
        });

        divisao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        divisao.setText(" ÷");
        divisao.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        divisao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        divisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisaoActionPerformed(evt);
            }
        });

        inputV2.setForeground(new java.awt.Color(0, 0, 0));
        inputV2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputV2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputV2ActionPerformed(evt);
            }
        });

        inputV1.setForeground(new java.awt.Color(0, 0, 0));
        inputV1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        inputV1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputV1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("RESULTADO:");

        resultadoCalculo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(valor1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputV1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(inputV2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resultadoCalculo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(soma, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(subtracao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(multiplicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(divisao, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor1)
                    .addComponent(inputV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soma)
                    .addComponent(subtracao)
                    .addComponent(multiplicacao)
                    .addComponent(divisao))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(resultadoCalculo))
                .addGap(39, 39, 39))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputV1ActionPerformed

    }//GEN-LAST:event_inputV1ActionPerformed

    private void inputV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputV2ActionPerformed

    }//GEN-LAST:event_inputV2ActionPerformed

    private void somaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_somaActionPerformed
        if (inputV1.getText().isEmpty() || inputV2.getText().isEmpty()) {
            resultadoCalculo.setText("0");
        } else {
            Calculadora calc = new Calculadora(Integer.parseInt(inputV1.getText()), Integer.parseInt(inputV2.getText()));
            resultadoCalculo.setText(calc.soma(Integer.parseInt(inputV1.getText()), Integer.parseInt(inputV2.getText())) + "");
        }
    }//GEN-LAST:event_somaActionPerformed

    private void subtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtracaoActionPerformed
        if (inputV1.getText().isEmpty() || inputV2.getText().isEmpty()) {
            resultadoCalculo.setText("0");
        } else {
            Calculadora calc = new Calculadora(Integer.parseInt(inputV1.getText()), Integer.parseInt(inputV2.getText()));
            resultadoCalculo.setText(calc.subtracao(Integer.parseInt(inputV1.getText()), Integer.parseInt(inputV2.getText())) + "");
        }
    }//GEN-LAST:event_subtracaoActionPerformed

    private void multiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplicacaoActionPerformed
        if (inputV1.getText().isEmpty() || inputV2.getText().isEmpty()) {
            resultadoCalculo.setText("0");
        } else {
            Calculadora calc = new Calculadora(Integer.parseInt(inputV1.getText()), Integer.parseInt(inputV2.getText()));
            resultadoCalculo.setText(calc.multiplicacao(Integer.parseInt(inputV1.getText()), Integer.parseInt(inputV2.getText())) + "");
        }
    }//GEN-LAST:event_multiplicacaoActionPerformed

    private void divisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisaoActionPerformed
        if (inputV1.getText().isEmpty() || inputV2.getText().isEmpty()) {
            resultadoCalculo.setText("0");
        } else {
            Calculadora calc = new Calculadora(Integer.parseInt(inputV1.getText()), Integer.parseInt(inputV2.getText()));
            resultadoCalculo.setText(calc.divisao(Integer.parseInt(inputV1.getText()), Integer.parseInt(inputV2.getText())) + "");
        }
    }//GEN-LAST:event_divisaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton divisao;
    private javax.swing.JTextField inputV1;
    private javax.swing.JTextField inputV2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton multiplicacao;
    private javax.swing.JLabel resultadoCalculo;
    private javax.swing.JButton soma;
    private javax.swing.JButton subtracao;
    private javax.swing.JLabel valor1;
    // End of variables declaration//GEN-END:variables
}
